# This is a basic workflow to help you get started with Actions

name: make-weasel

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Capture current date
        run: echo "DATE=$(date +%F)" >> $GITHUB_ENV

      - name: makensis
        # You may pin to the exact commit or the version.
        # uses: joncloud/makensis-action@05fcb06c41af46da367cb27b8948be9524c3bcec
        uses: joncloud/makensis-action@v3.7
        with:
          # Path to the .nsi script file
          script-file: weaselCustomPack/nsiBuild/install-custom.nsi
          # Arguments to makensis.exe
          arguments: ""
          additional-plugin-paths: ""
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Weasel_${{ env.DATE }}.exe
          path: weaselCustomPack/nsiBuild/archives\weasel-installer.exe
